name: Run Script and Upload Artifact
on:
  # 手动触发（通过 GitHub 网页端）
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest  # 也可改用 windows-latest 或 macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.14  # 根据项目需求调整版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装项目依赖

      - name: Run main.py with parameters
        run: |
          # 使用环境变量传递参数（安全方式）
          python main.py -u hiyondw753 -p 3biu6car

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          # 替换为实际生成的文件路径（需根据项目调整）
          path: |
            ./*
