name: Build Windows Executable
on:
  # 触发条件：手动触发（可通过 GitHub 网页端操作）或代码推送
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.10  # 选择项目兼容的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # 安装打包工具

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name=DepotManifestGen main.py
          # 可选参数说明：
          # --onefile：打包为单个可执行文件
          # --name：指定输出文件名
          # 更多参数见 PyInstaller 文档

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/DepotManifestGen.exe  # 打包后的文件路径
